<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ElektronickePosudky.Application\ElektronickePosudky.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data/" />
    <Folder Include="Data/Configurations/" />
    <Folder Include="Repositories/" />
    <Folder Include="Services/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
