using ElektronickePosudky.Application.Features.Posudky.Queries;
using ElektronickePosudky.Application.Interfaces;
using ElektronickePosudky.Application.Repositories;
using ElektronickePosudky.Domain.Entities.PosudekAggregate;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace ElektronickePosudky.Tests;

public class GetPosudekPdfQueryHandlerTests
{
    private readonly Mock<IPosudekRepository> _mockRepository;
    private readonly Mock<IPdfExportService> _mockPdfService;
    private readonly Mock<ILogger<GetPosudekPdfQueryHandler>> _mockLogger;
    private readonly GetPosudekPdfQueryHandler _handler;

    public GetPosudekPdfQueryHandlerTests()
    {
        _mockRepository = new Mock<IPosudekRepository>();
        _mockPdfService = new Mock<IPdfExportService>();
        _mockLogger = new Mock<ILogger<GetPosudekPdfQueryHandler>>();

        _handler = new GetPosudekPdfQueryHandler(
            _mockRepository.Object,
            _mockPdfService.Object,
            _mockLogger.Object
        );
    }

    [Fact]
    public async Task Handle_PosudekExists_ReturnsPdfBytes()
    {
        var query = new GetPosudekPdfQuery(Guid.NewGuid(), "corr-123");

        var dummyPosudek = new Mock<PosudekRo>().Object;

        var expectedPdfBytes = new byte[] { 1, 2, 3, 4, 5 };

        _mockRepository
            .Setup(repo => repo.GetByIdAsync(query.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(dummyPosudek);

        _mockPdfService
            .Setup(service => service.GeneratePosudekPdf(dummyPosudek))
            .Returns(expectedPdfBytes);

        var result = await _handler.Handle(query, CancellationToken.None);

        result.Should().NotBeNull("because the Posudek exists and PDF generation was successful");
        result.Should().BeEquivalentTo(expectedPdfBytes, "because the handler should return the exact bytes generated by the PDF service");

        _mockRepository.Verify(repo => repo.GetByIdAsync(query.Id, It.IsAny<CancellationToken>()), Times.Once);
        _mockPdfService.Verify(service => service.GeneratePosudekPdf(dummyPosudek), Times.Once);
    }

    [Fact]
    public async Task Handle_PosudekDoesNotExist_ReturnsNull_AndDoesNotCallPdfService()
    {
        var query = new GetPosudekPdfQuery(Guid.NewGuid(), "corr-123");

        _mockRepository
            .Setup(repo => repo.GetByIdAsync(query.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync((PosudekRo)null!);

        var result = await _handler.Handle(query, CancellationToken.None);

        result.Should().BeNull("because the Posudek was not found in the database");

        _mockRepository.Verify(repo => repo.GetByIdAsync(query.Id, It.IsAny<CancellationToken>()), Times.Once);

        _mockPdfService.Verify(service => service.GeneratePosudekPdf(It.IsAny<PosudekRo>()), Times.Never);
    }

    [Fact]
    public async Task Handle_RepositoryThrowsException_ThrowsException()
    {
        // Arrange
        var query = new GetPosudekPdfQuery(Guid.NewGuid(), "corr-123");

        _mockRepository
            .Setup(repo => repo.GetByIdAsync(query.Id, It.IsAny<CancellationToken>()))
            .ThrowsAsync(new Exception("Database connection failed"));

        Func<Task> act = async () => await _handler.Handle(query, CancellationToken.None);

        await act.Should().ThrowAsync<Exception>()
            .WithMessage("Database connection failed");

        _mockPdfService.Verify(service => service.GeneratePosudekPdf(It.IsAny<PosudekRo>()), Times.Never);
    }

    [Fact]
    public async Task Handle_PdfServiceThrowsException_ThrowsException()
    {
        var query = new GetPosudekPdfQuery(Guid.NewGuid(), "corr-123");
        var dummyPosudek = new Mock<PosudekRo>().Object;

        _mockRepository
            .Setup(repo => repo.GetByIdAsync(query.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(dummyPosudek);

        _mockPdfService
            .Setup(service => service.GeneratePosudekPdf(dummyPosudek))
            .Throws(new InvalidOperationException("PDF Generation Engine failed"));

        Func<Task> act = async () => await _handler.Handle(query, CancellationToken.None);

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("PDF Generation Engine failed");
    }
}