// <auto-generated />
using System;
using ElektronickePosudky.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElektronickePosudky.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406025036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.Ciselnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlatnostDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlatnostOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrekladyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciselniky");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.CiselnikPolozka", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CiselnikKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrekladyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RodicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CiselnikPolozky");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekHarmonizovanyKod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpresneniText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PosudekZpusobilostId");

                    b.ToTable("PosudkyRo_HarmonizovaneKody", (string)null);
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekHistorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumOperace")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PosudekRoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoId");

                    b.ToTable("PosudkyRo_Historie", (string)null);
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekNarodniKod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpresneniText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PosudekZpusobilostId");

                    b.ToTable("PosudkyRo_NarodniKody", (string)null);
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekRo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PosudkyRo", (string)null);
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekSkupinaRo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekZpusobilostId");

                    b.ToTable("PosudkyRo_SkupinyRO", (string)null);
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekZpusobilost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerzeZaznamu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoId");

                    b.ToTable("PosudkyRo_Zpusobilosti", (string)null);
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekHarmonizovanyKod", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekZpusobilost", null)
                        .WithMany("HarmonizovaneKody")
                        .HasForeignKey("PosudekZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "HarmonizovanyKod", b1 =>
                        {
                            b1.Property<Guid>("PosudekHarmonizovanyKodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekHarmonizovanyKodId");

                            b1.ToTable("PosudkyRo_HarmonizovaneKody");

                            b1.WithOwner()
                                .HasForeignKey("PosudekHarmonizovanyKodId");
                        });

                    b.OwnsMany("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "SkupinaRo", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("PosudekHarmonizovanyKodId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PosudekHarmonizovanyKodId");

                            b1.ToTable("PosudkyRo_HarmonizovaneKody_SkupinyRO_Items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PosudekHarmonizovanyKodId");
                        });

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "UpresneniKod", b1 =>
                        {
                            b1.Property<Guid>("PosudekHarmonizovanyKodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekHarmonizovanyKodId");

                            b1.ToTable("PosudkyRo_HarmonizovaneKody");

                            b1.WithOwner()
                                .HasForeignKey("PosudekHarmonizovanyKodId");
                        });

                    b.Navigation("HarmonizovanyKod")
                        .IsRequired();

                    b.Navigation("SkupinaRo");

                    b.Navigation("UpresneniKod");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekHistorie", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekRo", null)
                        .WithMany("Historie")
                        .HasForeignKey("PosudekRoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.ZdravotnickyPracovnikVO", "Lekar", b1 =>
                        {
                            b1.Property<Guid>("PosudekHistorieId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Jmeno")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("KrzpId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Odbornost")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Prijmeni")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TitulPred")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TitulZa")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekHistorieId");

                            b1.ToTable("PosudkyRo_Historie");

                            b1.WithOwner()
                                .HasForeignKey("PosudekHistorieId");
                        });

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.PoskytovatelVO", "Poskytovatel", b1 =>
                        {
                            b1.Property<Guid>("PosudekHistorieId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Adresa")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ico")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nazev")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekHistorieId");

                            b1.ToTable("PosudkyRo_Historie");

                            b1.WithOwner()
                                .HasForeignKey("PosudekHistorieId");
                        });

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "TypOperace", b1 =>
                        {
                            b1.Property<Guid>("PosudekHistorieId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekHistorieId");

                            b1.ToTable("PosudkyRo_Historie");

                            b1.WithOwner()
                                .HasForeignKey("PosudekHistorieId");
                        });

                    b.Navigation("Lekar")
                        .IsRequired();

                    b.Navigation("Poskytovatel")
                        .IsRequired();

                    b.Navigation("TypOperace")
                        .IsRequired();
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekNarodniKod", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekZpusobilost", null)
                        .WithMany("NarodniKody")
                        .HasForeignKey("PosudekZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "NarodniKod", b1 =>
                        {
                            b1.Property<Guid>("PosudekNarodniKodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekNarodniKodId");

                            b1.ToTable("PosudkyRo_NarodniKody");

                            b1.WithOwner()
                                .HasForeignKey("PosudekNarodniKodId");
                        });

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "SkupinaRo", b1 =>
                        {
                            b1.Property<Guid>("PosudekNarodniKodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekNarodniKodId");

                            b1.ToTable("PosudkyRo_NarodniKody");

                            b1.WithOwner()
                                .HasForeignKey("PosudekNarodniKodId");
                        });

                    b.Navigation("NarodniKod")
                        .IsRequired();

                    b.Navigation("SkupinaRo")
                        .IsRequired();
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekRo", b =>
                {
                    b.OwnsOne("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekHlavicka", "Hlavicka", b1 =>
                        {
                            b1.Property<Guid>("PosudekRoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DatumVystaveni")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DatumVytvoreni")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("PlatnostDo")
                                .HasColumnType("datetime2");

                            b1.Property<string>("VerzeZaznamu")
                                .IsConcurrencyToken()
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekRoId");

                            b1.ToTable("PosudkyRo");

                            b1.WithOwner()
                                .HasForeignKey("PosudekRoId");

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "DruhPosudku", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CiselnikKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("CiselnikVerze")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PolozkaKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "DruhProhlidky", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CiselnikKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("CiselnikVerze")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PolozkaKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "OdbornostLekare", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CiselnikKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("CiselnikVerze")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PolozkaKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.PoskytovatelVO", "PoskytovatelZdravotnickychSluzeb", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Adresa")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Ico")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Nazev")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "StavPosudku", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CiselnikKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("CiselnikVerze")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PolozkaKod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.ZdravotnickyPracovnikVO", "ZdravotnickyPracovnik", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Jmeno")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("KrzpId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Odbornost")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Prijmeni")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("TitulPred")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("TitulZa")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.OwnsOne("ElektronickePosudky.Domain.ValueObjects.PacientVO", "Pacient", b2 =>
                                {
                                    b2.Property<Guid>("PosudekHlavickaPosudekRoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Adresa")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("DatumNarozeni")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("Doklad")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Email")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Jmeno")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Pohlavi")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Prijmeni")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Rid")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PosudekHlavickaPosudekRoId");

                                    b2.ToTable("PosudkyRo");

                                    b2.WithOwner()
                                        .HasForeignKey("PosudekHlavickaPosudekRoId");
                                });

                            b1.Navigation("DruhPosudku")
                                .IsRequired();

                            b1.Navigation("DruhProhlidky")
                                .IsRequired();

                            b1.Navigation("OdbornostLekare")
                                .IsRequired();

                            b1.Navigation("Pacient")
                                .IsRequired();

                            b1.Navigation("PoskytovatelZdravotnickychSluzeb")
                                .IsRequired();

                            b1.Navigation("StavPosudku")
                                .IsRequired();

                            b1.Navigation("ZdravotnickyPracovnik")
                                .IsRequired();
                        });

                    b.Navigation("Hlavicka")
                        .IsRequired();
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekSkupinaRo", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekZpusobilost", null)
                        .WithMany("SkupinyRidicskehoOpravneni")
                        .HasForeignKey("PosudekZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "SkupinaRo", b1 =>
                        {
                            b1.Property<Guid>("PosudekSkupinaRoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekSkupinaRoId");

                            b1.ToTable("PosudkyRo_SkupinyRO");

                            b1.WithOwner()
                                .HasForeignKey("PosudekSkupinaRoId");
                        });

                    b.Navigation("SkupinaRo")
                        .IsRequired();
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekZpusobilost", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekRo", null)
                        .WithMany("Zpusobilosti")
                        .HasForeignKey("PosudekRoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "SkupinaZadateleRidic", b1 =>
                        {
                            b1.Property<Guid>("PosudekZpusobilostId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekZpusobilostId");

                            b1.ToTable("PosudkyRo_Zpusobilosti");

                            b1.WithOwner()
                                .HasForeignKey("PosudekZpusobilostId");
                        });

                    b.OwnsOne("ElektronickePosudky.Domain.ValueObjects.CiselnikPolozkaReference", "Vysledek", b1 =>
                        {
                            b1.Property<Guid>("PosudekZpusobilostId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CiselnikKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CiselnikVerze")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PolozkaKod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PosudekZpusobilostId");

                            b1.ToTable("PosudkyRo_Zpusobilosti");

                            b1.WithOwner()
                                .HasForeignKey("PosudekZpusobilostId");
                        });

                    b.Navigation("SkupinaZadateleRidic")
                        .IsRequired();

                    b.Navigation("Vysledek")
                        .IsRequired();
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekRo", b =>
                {
                    b.Navigation("Historie");

                    b.Navigation("Zpusobilosti");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekAggregate.PosudekZpusobilost", b =>
                {
                    b.Navigation("HarmonizovaneKody");

                    b.Navigation("NarodniKody");

                    b.Navigation("SkupinyRidicskehoOpravneni");
                });
#pragma warning restore 612, 618
        }
    }
}
